### ISSUE TITLE
no such column: cmsplugin_filer_image_filerimage.link_attributes

### ISSUE THREAD

**Issue by TheDeadOne** [divio/cmsplugin-filer#246]
When I try to delete the plug-in (video) from a page, I receive an error "django.db.utils.OperationalError: no such column: cmsplugin_filer_image_filerimage.link_attributes". I tried to remove it using toolbar and tried to use command `python manage.py cms delete-orphaned-plugins`. In both cases, there is the same error.

Python 2.7.10
Django 1.9.7
django-cms 3.3.0
cmsplugin-filer 1.1.1

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\core\management\__ini
t__.py", line 353, in execute_from_command_line
    utility.execute()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\core\management\__ini
t__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\core\management\base.
py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\core\management\base.
py", line 399, in execute
    output = self.handle(*args, **options)
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\management\commands\subc
ommands\base.py", line 86, in handle
    command.handle(*args, **options)
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\management\commands\subc
ommands\delete_orphaned_plugins.py", line 52, in handle
    instance.delete()
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\models\pluginmodel.py",
line 484, in delete
    super(CMSPlugin, self).delete(*args, **kwargs)
  File "D:\Projects\evrysoft\env2\lib\site-packages\treebeard\models.py", line 5
06, in delete
    self.__class__.objects.filter(pk=self.pk).delete()
  File "D:\Projects\evrysoft\env2\lib\site-packages\treebeard\mp_tree.py", line
98, in delete
    super(MP_NodeQuerySet, qset).delete()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\query.py",
line 599, in delete
    collector.collect(del_query)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\deletion.py
", line 230, in collect
    elif sub_objs:
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\query.py",
line 266, in __nonzero__
    return type(self).__bool__(self)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\query.py",
line 262, in __bool__
    self._fetch_all()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\query.py",
line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\query.py",
line 52, in __iter__
    results = compiler.execute_sql()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\models\sql\compile
r.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\backends\utils.py"
, line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\backends\utils.py"
, line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\utils.py", line 95
, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\backends\utils.py"
, line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\db\backends\sqlite3\b
ase.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: cmsplugin_filer_image_filerima
ge.link_attributes
```

**Comment by TheDeadOne** [comment]
The problem was in the djangocms-installer. It creates in settings

```
MIGRATION_MODULES = {
    'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
    'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
    'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
    'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
    'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django'
}
```

After removing MIGRATION_MODULES setting everything goes fine.

**Comment by yakky** [comment]
@TheDeadOne did you updated cmsplugin-filer after the project creation?
